name: Renovate

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 */3 * * *'

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Renovate
        uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
